name: Test Custom Action

on:
  push:
  workflow_dispatch:

jobs:
  run-custom-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run custom action
        uses: tanishka1410/custom-action-challenge

